### ISSUE TITLE
Not working with internal Bluetooth

### ISSUE THREAD

**Issue by davidwinegar** [mgigirey/iBeaconSwiftOSX#1]
I can confirm that this is not working with my Mac mini internal Blutooth.  I have yet to find a virtual beacon that will work.

**Comment by lacek** [comment]
Can confirm this doesn't work on my Macbook Pro with Yosemite (10.10.2).

**Comment by mgigirey** [comment]
It works with external Bluetooth 4.0 (BLE) USB dongle.

**Comment by lacek** [comment]
Suggest to state that this only work with external BLE dongle. It's kinda misleading now.

**Comment by mgigirey** [comment]
Blame Apple :-) 
http://stackoverflow.com/a/27542365/3824765

**Comment by mgigirey** [comment]
Maybe in the future Apple will fix this for internal Bluetooth, in the meantime just works with external.
